"""Content-addressed AI response caches.

The cache key deliberately includes the canonical input hash, model name and
prompt-template version.  Changing any one of those values creates a new
entry, preventing stale analyses after a prompt or model upgrade.
"""

from __future__ import annotations

import hashlib
import json
import os
import sqlite3
import tempfile
from collections.abc import Mapping
from pathlib import Path
from typing import Any, Protocol

from .models import AIUsage, AnalysisKind, AnalysisResult, CacheKey


def canonical_json(value: object) -> str:
    """Stable JSON used for input hashing and cache serialization."""

    return json.dumps(_redact_secrets(value), ensure_ascii=False, sort_keys=True, separators=(",", ":"), default=str)


def input_hash(value: object) -> str:
    return hashlib.sha256(canonical_json(value).encode("utf-8")).hexdigest()


def make_cache_key(
    payload: object,
    *,
    model: str,
    prompt_version: str,
    kind: AnalysisKind | str,
) -> CacheKey:
    digest = input_hash(payload)
    analysis_kind = AnalysisKind(kind).value
    material = f"{digest}\x00{model}\x00{prompt_version}\x00{analysis_kind}"
    value = hashlib.sha256(material.encode("utf-8")).hexdigest()
    return CacheKey(value, digest, str(model), str(prompt_version), analysis_kind)


class AnalysisCache(Protocol):
    def get(self, key: CacheKey | str) -> AnalysisResult | None: ...

    def set(self, key: CacheKey | str, result: AnalysisResult) -> None: ...


class NullAnalysisCache:
    """Explicit no-cache implementation."""

    def get(self, key: CacheKey | str) -> AnalysisResult | None:
        return None

    def set(self, key: CacheKey | str, result: AnalysisResult) -> None:
        return None


class FileAnalysisCache:
    """Atomic JSON-file cache suitable for a portable local workspace."""

    def __init__(self, root: str | Path = "data/ai-cache") -> None:
        self.root = Path(root).expanduser()
        self.root.mkdir(parents=True, exist_ok=True)

    def _path(self, key: CacheKey | str) -> Path:
        value = key.value if isinstance(key, CacheKey) else str(key)
        # A cache key is generated by us, but rejecting path separators keeps
        # this safe when a caller manually supplies a key in a test.
        safe = "".join(char for char in value if char in "0123456789abcdefABCDEF-_" )
        if not safe:
            raise ValueError("invalid cache key")
        return self.root / f"{safe}.json"

    def get(self, key: CacheKey | str) -> AnalysisResult | None:
        path = self._path(key)
        try:
            payload = json.loads(path.read_text(encoding="utf-8"))
        except (FileNotFoundError, json.JSONDecodeError, OSError):
            return None
        if not isinstance(payload, Mapping):
            return None
        result = AnalysisResult.from_dict(payload)
        # Refuse an accidentally mismatched file; callers can safely retry.
        expected = key.value if isinstance(key, CacheKey) else str(key)
        if result.cache_key and result.cache_key != expected:
            return None
        return result

    def set(self, key: CacheKey | str, result: AnalysisResult) -> None:
        path = self._path(key)
        payload = result.to_dict()
        payload["cache_key"] = key.value if isinstance(key, CacheKey) else str(key)
        text = json.dumps(_redact_secrets(payload), ensure_ascii=False, indent=2, sort_keys=True) + "\n"
        path.parent.mkdir(parents=True, exist_ok=True)
        fd, temp_name = tempfile.mkstemp(prefix=f".{path.stem}.", suffix=".tmp", dir=path.parent)
        try:
            with os.fdopen(fd, "w", encoding="utf-8") as handle:
                handle.write(text)
                handle.flush()
                os.fsync(handle.fileno())
            os.replace(temp_name, path)
        finally:
            try:
                os.unlink(temp_name)
            except FileNotFoundError:
                pass

    put = set


FileCache = FileAnalysisCache


class SQLiteAnalysisCache:
    """SQLite-backed cache.

    It can point at the study database; the cache uses its own table and does
    not alter the existing ``papers``/``questions`` schema.
    """

    def __init__(self, database: str | Path | sqlite3.Connection = "data/fenbi-study.db") -> None:
        self._owns_connection = not isinstance(database, sqlite3.Connection)
        if self._owns_connection:
            if str(database) == ":memory:":
                self.connection = sqlite3.connect(":memory:")
            else:
                path = Path(database).expanduser()
                path.parent.mkdir(parents=True, exist_ok=True)
                self.connection = sqlite3.connect(str(path))
        else:
            self.connection = database
        self.connection.row_factory = sqlite3.Row
        self.connection.execute(
            """
            CREATE TABLE IF NOT EXISTS ai_analysis_cache (
                cache_key TEXT PRIMARY KEY,
                input_hash TEXT NOT NULL,
                model TEXT NOT NULL,
                prompt_version TEXT NOT NULL,
                analysis_kind TEXT NOT NULL,
                payload_json TEXT NOT NULL,
                created_at TEXT NOT NULL
            )
            """
        )
        self.connection.commit()

    def get(self, key: CacheKey | str) -> AnalysisResult | None:
        value = key.value if isinstance(key, CacheKey) else str(key)
        row = self.connection.execute(
            "SELECT payload_json FROM ai_analysis_cache WHERE cache_key = ?", (value,)
        ).fetchone()
        if row is None:
            return None
        try:
            payload = json.loads(row["payload_json"])
            result = AnalysisResult.from_dict(payload)
        except (TypeError, ValueError, json.JSONDecodeError):
            return None
        expected = key.value if isinstance(key, CacheKey) else str(key)
        if result.cache_key and result.cache_key != expected:
            return None
        return result

    def set(self, key: CacheKey | str, result: AnalysisResult) -> None:
        cache = key if isinstance(key, CacheKey) else CacheKey(
            str(key), result.input_hash, result.model, result.prompt_version, result.kind.value
        )
        payload = result.to_dict()
        payload["cache_key"] = cache.value
        self.connection.execute(
            """
            INSERT INTO ai_analysis_cache
                (cache_key, input_hash, model, prompt_version, analysis_kind, payload_json, created_at)
            VALUES (?, ?, ?, ?, ?, ?, ?)
            ON CONFLICT(cache_key) DO UPDATE SET
                payload_json=excluded.payload_json,
                created_at=excluded.created_at
            """,
            (
                cache.value,
                cache.input_hash,
                cache.model,
                cache.prompt_version,
                cache.kind,
                json.dumps(_redact_secrets(payload), ensure_ascii=False, sort_keys=True),
                str(payload.get("created_at", "")),
            ),
        )
        self.connection.commit()

    put = set

    def close(self) -> None:
        if self._owns_connection:
            self.connection.close()


SQLiteCache = SQLiteAnalysisCache


class CompositeAnalysisCache:
    """Write-through cache useful when a study DB and portable files are both desired."""

    def __init__(self, *caches: AnalysisCache) -> None:
        self.caches = tuple(cache for cache in caches if cache is not None)

    def get(self, key: CacheKey | str) -> AnalysisResult | None:
        for cache in self.caches:
            result = cache.get(key)
            if result is not None:
                # Warm earlier caches only through explicit ``set``; avoiding a
                # write here keeps read-only callers side-effect free.
                return result
        return None

    def set(self, key: CacheKey | str, result: AnalysisResult) -> None:
        for cache in self.caches:
            cache.set(key, result)

    put = set


HybridAnalysisCache = CompositeAnalysisCache


def _redact_secrets(value: object, key: str | None = None) -> object:
    if key and _looks_secret(key):
        return "[REDACTED]"
    if isinstance(value, Mapping):
        result: dict[str, object] = {}
        for raw_key, raw_value in value.items():
            name = str(raw_key)
            if _looks_secret(name):
                continue
            result[name] = _redact_secrets(raw_value, name)
        return result
    if isinstance(value, (list, tuple)):
        return [_redact_secrets(item) for item in value]
    if isinstance(value, (str, int, float, bool)) or value is None:
        return value
    return str(value)


def _looks_secret(key: str) -> bool:
    name = key.lower().replace("-", "_")
    return any(token in name for token in ("api_key", "apikey", "access_token", "refresh_token", "password", "passwd", "cookie", "authorization", "secret"))

