"""USB/ADB capture primitives used by the desktop P2 workflow.

The module is deliberately dependency-light and keeps all device I/O behind
``AdbTransport``.  ``FakeAdbTransport`` is suitable for offline tests; the
real implementation only invokes an explicitly configured ``adb`` executable.
"""

from .adb import (
    ADBDevice,
    AdbCapture,
    AdbCaptureAdapter,
    AdbCaptureController,
    AdbDevice,
    AdbError,
    AdbTransport,
    CaptureError,
    CaptureController,
    DeviceInfo,
    DeviceState,
    FakeAdbTransport,
    PageChange,
    PageChangeDetector,
    RealAdbTransport,
    ScreenSize,
    Screenshot,
    ScreenshotArtifact,
    capture_screenshot,
    detect_page_change,
    is_page_changed,
    make_screenshot,
    parse_devices_output,
    parse_wm_density,
    parse_wm_size,
    stable_image_hash,
    screenshot_hash,
    stable_png_hash,
    stable_screenshot_hash,
)
from .lan_auth import (
    EMPTY_SHA256,
    is_allowed_lan_endpoint,
    is_private_lan_host,
    sign_lan_request,
    verify_lan_request,
)
from .lan_server import (
    DEFAULT_PORT,
    LanReceiveServer,
    format_pairing_code,
    local_ipv4_addresses,
    make_pairing_secret,
    parse_pairing_code,
)
from .session import (
    CaptureSession,
    CaptureStatus,
    CaptureSessionStatus,
    CaptureStateError,
    SessionCheckpoint,
    load_capture_session,
    save_capture_session,
)

__all__ = [
    "AdbCaptureAdapter",
    "AdbCaptureController",
    "AdbCapture",
    "AdbDevice",
    "ADBDevice",
    "AdbError",
    "AdbTransport",
    "CaptureError",
    "CaptureController",
    "CaptureSession",
    "CaptureStatus",
    "CaptureSessionStatus",
    "CaptureStateError",
    "DEFAULT_PORT",
    "EMPTY_SHA256",
    "LanReceiveServer",
    "DeviceInfo",
    "DeviceState",
    "FakeAdbTransport",
    "PageChange",
    "PageChangeDetector",
    "RealAdbTransport",
    "ScreenSize",
    "Screenshot",
    "ScreenshotArtifact",
    "SessionCheckpoint",
    "capture_screenshot",
    "detect_page_change",
    "is_page_changed",
    "make_screenshot",
    "parse_devices_output",
    "parse_wm_density",
    "parse_wm_size",
    "format_pairing_code",
    "is_allowed_lan_endpoint",
    "is_private_lan_host",
    "load_capture_session",
    "local_ipv4_addresses",
    "make_pairing_secret",
    "parse_pairing_code",
    "save_capture_session",
    "sign_lan_request",
    "verify_lan_request",
    "stable_image_hash",
    "screenshot_hash",
    "stable_png_hash",
    "stable_screenshot_hash",
]
